### ISSUE TITLE
Use asyncpg rather psycopg2 for performance improvement

### ISSUE THREAD

**Issue by mishnit** [MePhew-GonteQ-Industries/zolza-hairstyles-api#2]
postgresql+asyncpg://<db_username>:<db_secret>@<db_host>:<db_port>/<db_name>
 
asyncpg: https://github.com/MagicStack/asyncpg
ref: https://makimo.com/blog/connect-to-postgresql-with-sqlalchemy-and-asyncio/

**Comment by Me-Phew** [comment]
Making current code asynchronous to make it suitable for asyncpg is too much work.
